# =============================================================================
# GEMINI AI SECURITY SCAN JOB
# =============================================================================
#
# Gemini AI is an AI-powered security review tool for pull requests
# This workflow uses Google's Gemini API to perform comprehensive security analysis
# Repository: https://github.com/google-gemini/gemini-cli-action
#
# PREREQUISITES:
# - Create your own GEMINI_API_KEY from https://aistudio.google.com/apikey
# - Set up GEMINI_API_KEY secret in your repository settings
#
# TO USE THIS JOB:
# 1. Copy this entire job definition into .github/workflows/ai-scan.yml
# 2. Replace the current jobs: definition with this one
# 3. Comment '/ai-review' on any pull request to trigger the scan
# 4. The AI will analyze code changes and provide security recommendations
# =============================================================================

on:
  workflow_call:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  ai-security-review:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/ai-review')
    runs-on: ubuntu-latest
    name: AI-powered Security Review

    steps:
      - name: React to comment
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'rocket'
            });

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: AI Security Review with Gemini
        uses: google-gemini/gemini-cli-action@66b02172598d8f25de3a0101b50ef368af182aeb # latest commit as of July 18, 2025
        with:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            You are an expert in CI/CD security and DevSecOps practices.
            Please review this pull request focusing on:

            1. Security vulnerabilities in the code changes
            2. CI/CD pipeline security best practices
            3. Infrastructure as Code (IaC) security issues
            4. Container and Docker security concerns
            5. Secrets management and exposure risks
            6. Dependency and supply chain security
            7. Access control and permissions
            8. Security scanning and compliance gaps

            Provide a comprehensive security review with:
            - Identified security issues (if any)
            - Risk assessment (High/Medium/Low)
            - Specific recommendations for fixes
            - Best practices suggestions

            Focus on actionable feedback that helps improve the security posture of this CI/CD pipeline.

            Analyze the changes in this pull request using git diff to examine the actual changes made.

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment results on PR
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const comment = `## 🤖 AI Security Review Results

            The AI security scan has been completed! 🚀

            **Triggered by:** @${{ github.event.comment.user.login }}
            **Command:** \`${{ github.event.comment.body }}\`

            > 💡 **Note:** Detailed analysis is currently logged in the workflow. Soon we'll display the full review here!

            Check the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for complete details.
            `;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
