
# =============================================================================
# TRUFFLEHOG SECRETS SCAN JOB
# =============================================================================
#
# TruffleHog is a secrets scan tool for finding credentials in code
# Repository: https://github.com/trufflesecurity/trufflehog
#
# TO USE THIS JOB:
# 1. Copy this entire job definition into .github/workflows/secrets-scan.yml
# 2. Replace the current jobs: definition with this one
# 3. The job will automatically scan the entire repository for secrets
# 4. The scan will fail if any secrets are found
# =============================================================================

jobs:
  secrets-scan:
    name: Secrets Scan with TruffleHog
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.scan-result.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Run TruffleHog secrets scanner
        id: scan-tool
        run: |
          # Install TruffleHog
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin

          # Run filesystem scan
          trufflehog filesystem . --results=verified,unknown --fail

      - name: Set scan result
        id: scan-result
        if: always()
        run: |
          if [ "${{ steps.scan-tool.outcome }}" == "success" ]; then
            echo "result=success" >> "$GITHUB_OUTPUT"
            echo "✅ Secrets scan passed - no secrets detected"
          else
            echo "result=failure" >> "$GITHUB_OUTPUT"
            echo "❌ Secrets scan failed - secrets detected in repository"
            exit 1
          fi
